CC = gcc
CFLAGS = -Wall -O2
OBJS = func0.o func1.o func2.o func3.o func4.o func5.o func6.o func7.o func8.o func9.o

all: encrypt decrypt

encrypt: encrypt.o encode.o $(OBJS)
	$(CC) -o $@ $^

decrypt: decrypt.o decode.o $(OBJS)
	$(CC) -o $@ $^

clean:
	rm encrypt decrypt *.o
